version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: VxJJuMVMYg0P+dDEYt5RkUm9WES+KdcrCNJNdDfImOQCJzZNhEWNty6jALgvgPFC
  artifact: /.*\.nupkg/